# KCometen6 Standalone Portable Configuration Profile

cometCount = 150
createInterval = 0.01
sizeScale = 2.0
timeScale = 2.6
bgMode = screenshot
customBgFile = 
customCeilingFile = 
customFloorFile = 
rotateComet = true
splitComet = true
curveComet = true
blitz = true
usePointSprites = true
colorMode = 3
maxFps = 60
mipmaps = true
useSystemdScreensaver = false
screensaverTimeout = 1
